### ISSUE TITLE
old files

### ISSUE THREAD

**Issue by Vescarea** [BSData/judge-dredd#2]
hey i have updated the files but cant get them on here the pull request doesnt show up with anything.

**Comment by amis92** [comment]
yeah but you've updated your own repo and not the fork you've made. :) wrong folder buddy! :D

**Comment by Vescarea** [comment]
dam lol soory my fail haha :) got a friend to guide me lol. Thanks

Sent from Samsung Mobile on O2

-------- Original message --------

**Comment by amis92** [comment]
You're welcome ;)

**Comment by Vescarea** [comment]
Hi another quick question the just realised current .cat file is very old, im uploading a new revised one. can the new one overwrite it?
ThanksEuan

Sent from Samsung Mobile on O2

-------- Original message --------

**Comment by amis92** [comment]
Okay, my bad I haven't checked what you've commited. First off, _don't_ save the files as `.catz`, but rather as `.cat`. Same with Game System. Please give Wiki a read, there are many helpful hints there.

Then, instead of creating new files, modify those already existing. Clone Git repo into `.../BattleScribe/data` folder and open directly from Catalogue/Game System editor. Then just save. And commit. And so on, as per Wiki.

Wiki link: https://github.com/BSData/bsdata/wiki/Developer-Guide

**Comment by amis92** [comment]
And also, if you want to remove old files, then just go on. However better practice is to update those existing, as I said.
