### ISSUE TITLE
[Anon] Bug report: Characters_(WG2019).catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/judge-dredd#23]
**File:** Characters_(WG2019).catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** There is problem with Judge Dredd and Judge Anderson, mainly in the rulebook it states (page 75)
"Dredd's primary personal weapons are his Lawgiver Mk2, a Day stick and Boot knife.
Judge Dredd may also be equipped with a M2000 Widowmaker or the Lawrod Mk5 for an additional notoriety cost."
So here we see it states may, and in battlescribe it gives error and states that Judge Dredd musthave one more selection from Judge Weapons even tho he already has Lawgiver option selected.

Plus there is no option for either him or Judge Anderson to take Lawmaster bike in their profile.

**Comment by JudgeRed** [comment]
![Capturea1](https://user-images.githubusercontent.com/77886951/110044902-337fd680-7d4a-11eb-93f0-ca7488f85d62.JPG)
(forgot to log in while writing upper comment)

P.s.
There is difference with Lawmasters and their weapons (p65)
Basic lawmaster is 12 notriety
plus variety of weapons depending is it Mk1,2,3
So that is a thing that also needs to be incorporated
![IMG_20210306_165609](https://user-images.githubusercontent.com/77886951/110212697-01cb5480-7e9d-11eb-9680-2a0dced358bd.jpg)

**Comment by skudfisher** [comment]
I know this is old but all issues mentioned here should be fixed in the latest update.
